language: cpp
sudo: required
dist: bionic
compiler:
  - gcc
os:
  - linux

before_install:
  - wget http://turbulentsoft.com/wp-content/uploads/2019/10/deps.tar.gz
  - mkdir -p deps && tar -xzf deps.tar.gz -C deps
  - sudo add-apt-repository -y ppa:cginternals
  - sudo apt-get install -y libsdl2-dev libassimp-dev libtinyxml2-dev libcppfs-dev libglm-dev rapidjson-dev libopenal-dev libvorbis-dev libogg-dev

before_script:
  - mkdir build
  - cd build

script:
  - cmake ..
  - make