e:\Projects\VulkanSDK\1.1.77.0\Bin32\glslangValidator.exe -V skeletalPhong.vert -o skeletalPhong.vert.spv
e:\Projects\VulkanSDK\1.1.77.0\Bin32\glslangValidator.exe -V phong.vert -o phong.vert.spv
e:\Projects\VulkanSDK\1.1.77.0\Bin32\glslangValidator.exe -V phong.frag -o phong.frag.spv
e:\Projects\VulkanSDK\1.1.77.0\Bin32\glslangValidator.exe -V skybox.vert -o skybox.vert.spv
e:\Projects\VulkanSDK\1.1.77.0\Bin32\glslangValidator.exe -V skybox.frag -o skybox.frag.spv
e:\Projects\VulkanSDK\1.1.77.0\Bin32\glslangValidator.exe -V simpleDepth.vert -o simpleDepth.vert.spv
e:\Projects\VulkanSDK\1.1.77.0\Bin32\glslangValidator.exe -V simpleSkeletalDepth.vert -o simpleSkeletalDepth.vert.spv
e:\Projects\VulkanSDK\1.1.77.0\Bin32\glslangValidator.exe -V simpleDepth.frag -o simpleDepth.frag.spv
e:\Projects\VulkanSDK\1.1.77.0\Bin32\glslangValidator.exe -V phongShadowMap.vert -o phongShadowMap.vert.spv
e:\Projects\VulkanSDK\1.1.77.0\Bin32\glslangValidator.exe -V phongShadowMap.frag -o phongShadowMap.frag.spv
e:\Projects\VulkanSDK\1.1.77.0\Bin32\glslangValidator.exe -V shadowMapRender.frag -o shadowMapRender.frag.spv
e:\Projects\VulkanSDK\1.1.77.0\Bin32\glslangValidator.exe -V phongWater.vert -o phongWater.vert.spv
e:\Projects\VulkanSDK\1.1.77.0\Bin32\glslangValidator.exe -V phongWater.frag -o phongWater.frag.spv
e:\Projects\VulkanSDK\1.1.77.0\Bin32\glslangValidator.exe -V phongWaterShadow.vert -o phongWaterShadow.vert.spv
e:\Projects\VulkanSDK\1.1.77.0\Bin32\glslangValidator.exe -V phongWaterShadow.frag -o phongWaterShadow.frag.spv