#!/bin/bash
for file in *.{vert,frag,geom,comp}
do
    if /home/darth/Software/shaderc/bin/glslc/glslc -c $file -o $file.spv
    then
        echo "Compiled $file."
    else
        exit 1
    fi
done